config:
  credentials: []
  project_repos:
    github.com/CERN-IT-INNOVATION/QuASK:
      branch: main
      repo: https://github.com/CERN-IT-INNOVATION/QuASK
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-carmine-slug.sh
        container: qc.acc_flabby-yellow-dunker
  QC.Doc:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lime-russel.sh
        container: qc.doc_sloppy-corn-bee
      github.com/CERN-IT-INNOVATION/QuASK git:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-flax-lemur.sh
        container: qc.doc_jumpy-copper-angelfish
      github.com/CERN-IT-INNOVATION/QuASK markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-yellow-oyster.sh
        container: qc.doc_silly-ivory-tarantula
      github.com/CERN-IT-INNOVATION/QuASK restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-sangria-dunker.sh
        container: qc.doc_stinky-buff-retriever
  QC.Lic:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-aqua-chinchilla.sh
        container: qc.lic_ready-ruby-otter
  QC.Sec:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-tangerine-angelfish.sh
        container: qc.sec_pokey-tangerine-mastiff
  QC.Sty:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-cream-dodo.sh
        container: qc.sty_chummy-harlequin-walrus
      github.com/CERN-IT-INNOVATION/QuASK jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-teal-zonkey.sh
        container: qc.sty_gamy-champagne-turtle
  QC.Uni:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-olive-rabbit.sh
        container: qc.uni_queasy-persimmon-tuatara
  QC.Ver:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-gold-sloth.sh
        container: qc.ver_whiny-wheat-uakari
timeout: 5400
