config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/QuASK:
      branch: main
      repo: https://github.com/IraitzM/QuASK
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/QuASK git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-charcoal-tapir.sh
        container: qc.acc_craggy-charcoal-dolphin
  QC.Doc:
    repos:
      github.com/IraitzM/QuASK find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-black-clam.sh
        container: qc.doc_bluesy-auburn-penguin
      github.com/IraitzM/QuASK git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-sangria-dormouse.sh
        container: qc.doc_smelly-xanthic-nightingale
      github.com/IraitzM/QuASK markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-indigo-dhole.sh
        container: qc.doc_boozy-olivine-havanese
      github.com/IraitzM/QuASK restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.messy-orchid-avocet.sh
        container: qc.doc_smelly-razzmatazz-tamarin
  QC.Lic:
    repos:
      github.com/IraitzM/QuASK licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-rose-oriole.sh
        container: qc.lic_randy-indigo-alligator
  QC.Sec:
    repos:
      github.com/IraitzM/QuASK bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-magenta-skunk.sh
        container: qc.sec_hasty-maroon-mist
  QC.Sty:
    repos:
      github.com/IraitzM/QuASK flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-pumpkin-bat.sh
        container: qc.sty_randy-magnolia-beetle
  QC.Uni:
    repos:
      github.com/IraitzM/QuASK pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-sangria-elephant.sh
        container: qc.uni_wiggy-purple-bloodhound
  QC.Ver:
    repos:
      github.com/IraitzM/QuASK get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-pink-wombat.sh
        container: qc.ver_fuzzy-harlequin-heron
timeout: 5400
