config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/QuASK:
      branch: main
      repo: https://github.com/IraitzM/QuASK
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/QuASK git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-viridian-barb.sh
        container: qc.acc_thirsty-blue-spitz
  QC.Doc:
    repos:
      github.com/IraitzM/QuASK find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-coral-fly.sh
        container: qc.doc_ugly-maroon-slug
      github.com/IraitzM/QuASK git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-periwinkle-jaguar.sh
        container: qc.doc_pokey-rust-eagle
      github.com/IraitzM/QuASK markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-persimmon-wildebeest.sh
        container: qc.doc_grumpy-harlequin-opossum
      github.com/IraitzM/QuASK restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-linen-wallaby.sh
        container: qc.doc_flimsy-tan-olm
  QC.Lic:
    repos:
      github.com/IraitzM/QuASK licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-sangria-hornet.sh
        container: qc.lic_wimpy-linen-fousek
  QC.Sec:
    repos:
      github.com/IraitzM/QuASK bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-burgundy-skunk.sh
        container: qc.sec_grumpy-tangerine-otter
  QC.Sty:
    repos:
      github.com/IraitzM/QuASK flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-periwinkle-monkey.sh
        container: qc.sty_jumpy-olive-hornet
  QC.Uni:
    repos:
      github.com/IraitzM/QuASK pytest:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cinnabar-lobster.sh
        container: qc.uni_stuffy-ecru-catfish
  QC.Ver:
    repos:
      github.com/IraitzM/QuASK get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-periwinkle-cattle.sh
        container: qc.ver_scaly-pink-wrasse
timeout: 5400
