config:
  credentials: []
  project_repos:
    github.com/CERN-IT-INNOVATION/QuASK:
      branch: main
      repo: https://github.com/CERN-IT-INNOVATION/QuASK
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-mauve-bongo.sh
        container: qc.acc_shaggy-pear-burmese
  QC.Doc:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-heliotrope-whale.sh
        container: qc.doc_foggy-thistle-slug
      github.com/CERN-IT-INNOVATION/QuASK git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-pumpkin-oyster.sh
        container: qc.doc_slaphappy-plum-hornet
      github.com/CERN-IT-INNOVATION/QuASK markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-persimmon-lemming.sh
        container: qc.doc_baggy-auburn-bird
      github.com/CERN-IT-INNOVATION/QuASK restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-smalt-foxhound.sh
        container: qc.doc_ugly-linen-dogfish
  QC.Lic:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-tomato-panda.sh
        container: qc.lic_shaky-denim-snake
  QC.Sec:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-indigo-uguisu.sh
        container: qc.sec_gummy-olive-gopher
  QC.Sty:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-linen-reindeer.sh
        container: qc.sty_whiny-azure-affenpinscher
      github.com/CERN-IT-INNOVATION/QuASK jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-ivory-forest.sh
        container: qc.sty_homely-brown-dalmatian
  QC.Uni:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK pytest:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-flax-antelope.sh
        container: qc.uni_stuffy-corn-crocodile
  QC.Ver:
    repos:
      github.com/CERN-IT-INNOVATION/QuASK get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-tan-otter.sh
        container: qc.ver_nippy-cream-hound
timeout: 5400
